CoreEcommerceUserPanal/Models/Brands.cs
using System;
using System.Collections.Generic;

namespace CoreEcommerceUserPanal.Models
{
    public partial class Brands
    {
        public Brands()
        {
            Products = new HashSet<Products>();
        }

        public int BrandId { get; set; }
        public string BrandName { get; set; }
        public string BrandDescription { get; set; }

        public ICollection<Products> Products { get; set; }
    }
}

CoreEcommerceUserPanal/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreEcommerceUserPanal.Models;
using Microsoft.AspNetCore.Mvc;

namespace CoreEcommerceUserPanal.Controllers
{
    public class BrandController : Controller
    {
       // ShoppingProjectFinalContext context = new ShoppingProjectFinalContext();
        private readonly ShoppingProjectFinalContext _context;

        public BrandController(ShoppingProjectFinalContext context)
        {
            _context = context;
        }
        public ViewResult Index()
        {
            var brand = _context.Brands.ToList();
            return View(brand);
        }
       
        public async Task<IActionResult> ProductDisplay(int? id)
        {
            var p = _context.Products.Where(x => x.BrandId == id).ToList();
            return View(p);
        }
        
        [HttpGet]
        public async Task<IActionResult> Get(int? id)

        {
            if (id == null)
            {
                return BadRequest();
            }
            var brand = await _context.Brands.FindAsync(id);
            if (brand == null)

            {
                return NotFound();
            }
            return Ok(brand);
        }
    }
}

CoreEcommerceUserPanal/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreEcommerceUserPanal.Helpers;
using CoreEcommerceUserPanal.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Stripe;

namespace CoreEcommerceUserPanal.Controllers
{
    [Route("cart")]
    public class CartController : Controller
    {
        ShoppingProjectFinalContext context = new ShoppingProjectFinalContext();
        //private readonly ShoppingProjectFinalContext _context;

        //public CartController(ShoppingProjectFinalContext context)
        //{
        //    _context = context;
        //}
        [Route("index")]
       
        public IActionResult Index()
        {

            var cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            foreach (var it in cart)
            {
                if (it.Quantity == it.Products.ProductQty)
                {
                    ViewBag.j = it.Products.ProductId;
                }
            }
            int i = 0;
            if (cart != null)
            {

                foreach (var item in cart)
                {
                    i++;
                }
                if (i != 0)
                {
                    ViewBag.cart = cart;
                    ViewBag.total = cart.Sum(item => item.Products.ProductPrice * item.Quantity);
                    if (SessionHelper.GetObjectFromJson<Customers>(HttpContext.Session, "cust")==null)
                    {
                        ViewBag.i = 0;
                    }
                    else
                    {
                        ViewBag.i = 1;
                    }
                    return View();
                }

            }
            return View("GoBack");
        }
        [Route("buy /{id}")]
        public IActionResult Buy(int id)
        {
            Products p = context.Products.Find(id);
            if (p.ProductQty < 1)
            {
                return RedirectToAction("OutofStock", "cart", new { @id = id });
            }
            if (SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session,"cart") == null)
            {
                List<Item> cart = new List<Item>();
                cart.Add(new Item
                {
                    Products = context.Products.Find(id),
                    Quantity = 1
                });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                List<Item> cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
                int index = isExist(id);
                if(index !=-1)
                {
                    cart[index].Quantity++;
;                }
                else
                {
                    cart.Add(new Item
                    {
                        Products = context.Products.Find(id),Quantity = 1 });
                    }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToAction("Index","Home");

        }
        [Route("OutofStock/{id}")]
        public IActionResult OutofStock(int id)
        {
            var detail = context.Products.Find(id);
            var cid = context.Products.Find(id);
            ViewBag.cname = context.Categories.Find(cid.ProductCategoryId);
            return View(detail);

        }
        [Route("Remove/{id}")]
        
            public IActionResult Remove(int id)
            {
                List<Item> cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
                int index = isExist(id);
                cart.RemoveAt(index);
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
                int j = int.Parse(HttpContext.Session.GetString("cartitem"));
                int i = 0;
                foreach (var item in cart)
                {
                    i++;
                }
                if (i != 0)
                {
                    j--;
                    HttpContext.Session.SetString("cartitem", j.ToString());
                }
                else
                {
                    HttpContext.Session.Remove("cartitem");
                    return View("GoBack");
                }
                return RedirectToAction("Index");

            }
        [Route("GoBack")]
        public IActionResult GoBack()
        {
            return View();
        }

            private int isExist(int id)
        {
            List<Item> cart = SessionHelper.GetObjectFromJson<List<Item>>
                (HttpContext.Session, "cart");
            for(int i=0;i<cart.Count;i++)
            {
                if(cart[i].Products.ProductId.Equals(id))
                {
                    return i;
                }
            }
            return -1;
        }
        [Route("Details/{id}")]
        public IActionResult Details(int id)
        {

            var detail = context.Products.Find(id);
            var cid = context.Products.Find(id);
            ViewBag.cname = context.Categories.Find(cid.ProductCategoryId);
            return View(detail);
        }
        [Route("Checkout")]
        [HttpGet]
        public IActionResult Checkout()
        {
            int i = 0;
            ViewBag.i = i;
            var checkout = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session,"cart");
            ViewBag.checkout = checkout;
            ViewBag.total = checkout.Sum(item => item.Products.ProductPrice * item.Quantity);
            string cust = HttpContext.Session.GetString("uname");
            Customers cus = context.Customers.Where(x => x.UserName == cust).SingleOrDefault();
            ViewBag.cus = cus;
            ViewBag.totalitem = checkout.Count();
            TempData["total"] = ViewBag.total;
            return View();
        }
        [Route ("Checkout")]
        [HttpPost]
        public IActionResult Checkout(Customers customer1, string stripeEmail, string stripeToken)
        {
            
         var c = context.Customers.Where(x => x.UserName == customer1.UserName).SingleOrDefault();
            c.FirstName = customer1.FirstName;
            c.LastName = customer1.LastName;
            c.UserName = customer1.UserName;
            c.EmailId = customer1.EmailId;
            c.Address = customer1.Address;
            c.PhoneNo = customer1.PhoneNo;
            c.Country = customer1.Country;
            c.State = customer1.State;
            c.Zip = customer1.Zip;
            context.SaveChanges();
                var amount = (TempData["total"]);
                Orders orders = new Orders()
                {
                    OrderPrice = Convert.ToSingle(amount),
                    OrderDate = DateTime.Now,
                    CustomerId = c.CustomerId

                };
                context.Orders.Add(orders);
            
                context.SaveChanges();
            TempData["orderId"] = orders.OrderId;
            var cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
                List<OrderProducts> OrderProducts = new List<OrderProducts>();

                for (int i = 0; i < cart.Count; i++)
                {
                    OrderProducts orderproducts = new OrderProducts()
                    {
                        OrderId = orders.OrderId,
                        ProductId = cart[i].Products.ProductId,
                        Quantity = cart[i].Quantity
                    };
                    OrderProducts.Add(orderproducts);
                }
                OrderProducts.ForEach(n => context.OrderProducts.Add(n));
                context.SaveChanges();
                TempData["cust"] = c.CustomerId;


           
                var customers = new CustomerService();
                var charges = new ChargeService();
                var Amount = TempData["total"];
                var order = TempData["orderId"];
                var custt = TempData["cust"];
                var customer = customers.Create(new CustomerCreateOptions
                {
                    Email = stripeEmail,
                    SourceToken = stripeToken
                });

                var charge = charges.Create(new ChargeCreateOptions
                {
                    Amount = 500,
                    Description = "Sample Charge",
                    Currency = "usd",
                    CustomerId = customer.Id
                });

                Payments payment = new Payments();
                {
                    payment.PaymentStripeId = charge.PaymentMethodId;
                    payment.Amount = Convert.ToInt32(Amount);
                    payment.Paymentdate = System.DateTime.Now;
                    payment.CardNo = Convert.ToInt32(charge.PaymentMethodDetails.Card.Last4);
                    payment.OrderId = Convert.ToInt32(order);
                    payment.CustomerId = Convert.ToInt32(custt);
                }

                context.Add<Payments>(payment);
                context.Payments.Add(payment);
                context.SaveChanges();
            TempData["pay"] = payment.PaymentId;
            return RedirectToAction("Invoice");
            
           // return RedirectToAction("Invoice","Cart");
            //}
            //return View();
        }

        public IActionResult PaymentIndex()
        {
            var checkout = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            ViewBag.checkout = checkout;
            ViewBag.total = checkout.Sum(item => item.Products.ProductPrice * item.Quantity);
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }


        [Route("Invoice")]
        public IActionResult Invoice()
        {

CoreEcommerceUserPanal/Views/Brand/Index.cshtml
@model IEnumerable<CoreEcommerceUserPanal.Models.Brands>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}



<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>Brand</h1>
            </div>
        </div>
    </div>
</section>
<!-- End Banner Area -->
<br />
<br /><br />
<br />



<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BrandId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BrandName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BrandDescription)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.BrandId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BrandName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BrandDescription)
                </td>
                <td>
                    <a asp-controller="Brand" asp-action="ProductDisplay" asp-route-id="@item.BrandId" class="btn btn-sm btn-outline-secondary">Choose</a>
                </td>
            </tr>
        }
    </tbody>
</table>

CoreEcommerceUserPanal/Views/Brand/ProductDisplay.cshtml
@model IEnumerable<CoreEcommerceUserPanal.Models.Products>
@{
    ViewData["Title"] = "ProductDisplay";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}


<!-- Start Banner Area -->
<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
            <div class="col-first">
                <h1>Product Display</h1>
            </div>
        </div>
    </div>
</section>
<!-- End Banner Area -->
<br />
<br /><br />
<br />



<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <img src="@item.ProductImage" class="bd-placeholder-img card-img-top" height="400" width="200" />
                        <div class="card-body">
                            <p class="card-text" style="font-weight:bold;">@item.ProductName</p>
                            <p class="card-text" style="font-weight:bold;">@item.ProductDescription</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    @*<button type="button" class="btn btn-sm btn-outline-secondary">View Details</button>*@
                                    @*<button type="button" class="btn btn-sm btn-outline-secondary">Add to Cart</button>*@
                                    <a asp-controller="Cart" asp-action="Buy" asp-route-id="@item.ProductId" onclick="alert('Added To cart')" class="btn btn-sm btn-outline-secondary"> Add to Cart </a>&nbsp;&nbsp;&nbsp;

                                    <a asp-controller="Cart" asp-action="details" asp-route-id="@item.ProductId" class="btn btn-sm btn-outline-secondary"> View Details</a>
                                </div>

                                <h5 class="text-muted">@item.ProductQty Left</h5>
                            </div>
                        </div>
                    </div>
                </div>
            }


        </div>
    </div>
</div>